### ISSUE TITLE
How to preprocess the Sentinel-2 images if I want to add cloud to them?

### ISSUE THREAD

**Issue by Yeah21** [cidcom/SatelliteCloudGenerator#4]
Hello, your work is very solid and useful. I tried to run your Example.py and got good performance on the RGB images cloud simulation task. Now I want to simulate the cloud on Sentinel-2 images with B2-B12 bands, what should I do in the data preprocessing?

**Comment by mikonvergence** [comment]
Hi! Thanks for the kind words.

This depends on what data you're working with.

It's quite crucial to match realistic magnitudes of the cloud component in individual bands of multi-spectral images, and this has been analysed a bit in the manuscript linked to this article: https://www.mdpi.com/2072-4292/15/17/4138

The key message is that these magnitudes will depend on how you normalise individual bands of your image. If you have access to some realy cloudy samples in the same format as your cloud-free images, you can approximate these magnitudes - again, this process is described in more detail in the manuscript. The extraction functions are included in https://github.com/strath-ai/SatelliteCloudGenerator/blob/main/src/band_magnitudes.py

If you have any more specific questions, please let me know!

**Comment by mikonvergence** [comment]
Also, there's an example of this in the main notebook: https://github.com/strath-ai/SatelliteCloudGenerator/blob/main/01-Usage-Examples.ipynb in the section **Multi-Spectral Data**

**Comment by Yeah21** [comment]
When I saw the title, I mistook it for the simulation of clouds based on the GAN network. You know, deep learning-based approaches have to ensure that data preprocessing is consistent. I can't find the optimization target when I look at the article. That's my problem. At present, I have solved my problem using your method, thanks again.

**Comment by mikonvergence** [comment]
Excellent, thanks.

Yes, generative models of any type can be used to approximate the probability distribution of cloudy images and sample from it. However, that approach could have both pros (optimised on real clouds directly) and cons (data bias, noise of the learning process). This aspect is discussed to some extent in the linked paper (https://www.mdpi.com/2072-4292/15/17/4138).

I am not actively working on this topic anymore, but a comparison study between this technique and some learning-based methods would be quite interesting to see!
