### ISSUE TITLE
Using the same channel mask for multiple images

### ISSUE THREAD

**Issue by zakiindra** [cidcom/SatelliteCloudGenerator#5]
First of all, I want to appreciate this work. It is very useful, and I'm currently using it for my research.
I want to use the same cloud pattern for multiple images, and I believe it is returned as `cmask` in the example. Is it possible to use the same cmask for different images? I am evaluating performance of ML model robustness against cloud and I want to apply the same cloud pattern to many images to observe if different patterns influence the performance.
Is there any way I can do it?

Thank you.

**Comment by mikonvergence** [comment]
Hi @zakiindra, thank you!

Yes, it is possible and I have done this before for my research I think.

Please have a look here:
https://github.com/strath-ai/SatelliteCloudGenerator/blob/d0787cbdc1b39a7976f89aa085f1430f3207eda6/src/CloudSimulator.py#L328-L333
* You can get the `cloud` component by setting `return_cloud` to `True`
* You can then use the `mix()` method as shown above to mix the returned cloud with any image
* Ultimately, the current code is not best adapted to it, but it is definitely possible by doing this as described above - if you have some ideas on how the current package could be expanded to allow this more easily, feel free to propose!

Let me know if this answers your doubts.
